spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tablebooking
    username: root
    password: 0000
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 개발 환경에서만 사용, 운영 환경에서는 validate로 변경 권장
    show-sql: true
  h2:
    console:
      enabled: true
