spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tablebooking
    username: root
    password: zerozero
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
      dialect: org.hibernate.dialect.MariaDBDialect  # Hibernate Dialect
  h2:
    console:
      enabled: true